// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: lumberjack/v1/lumberjack.proto

// Package lumberjack.v1 is the gRPC contract between the Lumberjack CLI
// (client) and the background daemon (server). The daemon owns the database
// and all worktree operations; the CLI is a thin client that calls into this
// API. See docs/prd.md ("Architecture: client / server split") and AGENTS.md.
//
// `lumberjack doctor` deliberately has no RPC here: it checks host
// prerequisites (git/gh) and must work even when the daemon is not running, so
// it stays entirely CLI-local.

package lumberjackv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LumberjackService_Health_FullMethodName           = "/lumberjack.v1.LumberjackService/Health"
	LumberjackService_InitRepository_FullMethodName   = "/lumberjack.v1.LumberjackService/InitRepository"
	LumberjackService_ListRepositories_FullMethodName = "/lumberjack.v1.LumberjackService/ListRepositories"
	LumberjackService_GetRepository_FullMethodName    = "/lumberjack.v1.LumberjackService/GetRepository"
	LumberjackService_SetLogin_FullMethodName         = "/lumberjack.v1.LumberjackService/SetLogin"
	LumberjackService_ListLogins_FullMethodName       = "/lumberjack.v1.LumberjackService/ListLogins"
	LumberjackService_ListWorktrees_FullMethodName    = "/lumberjack.v1.LumberjackService/ListWorktrees"
	LumberjackService_DeleteWorktree_FullMethodName   = "/lumberjack.v1.LumberjackService/DeleteWorktree"
	LumberjackService_Sync_FullMethodName             = "/lumberjack.v1.LumberjackService/Sync"
)

// LumberjackServiceClient is the client API for LumberjackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LumberjackService is served by `lumberjack daemon` over a local Unix domain
// socket (LUMBERJACK_SOCKET_PATH). Every user-facing CLI command maps to one
// of these RPCs.
type LumberjackServiceClient interface {
	// Health reports that the daemon is up. The CLI uses it to detect whether a
	// daemon is running before issuing other calls.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// InitRepository registers a repo — `lumberjack init .`.
	InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*InitRepositoryResponse, error)
	// ListRepositories lists tracked repos — `lumberjack repositories`.
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
	// GetRepository returns one repo's last-sync detail —
	// `lumberjack repositories NAME`.
	GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*GetRepositoryResponse, error)
	// SetLogin sets the gh account a repository operates under —
	// `lumberjack repositories NAME set-login LOGIN` or, from within a tracked
	// checkout, `lumberjack set-login LOGIN`. The daemon rejects a login that gh
	// is not authenticated as for the repository's host, or one that authenticates
	// but cannot reach the repository on GitHub.
	SetLogin(ctx context.Context, in *SetLoginRequest, opts ...grpc.CallOption) (*SetLoginResponse, error)
	// ListLogins returns the gh accounts authenticated for a repository's host —
	// the candidates set-login accepts. The CLI uses it to offer an interactive
	// picker when `set-login` is run without a login.
	ListLogins(ctx context.Context, in *ListLoginsRequest, opts ...grpc.CallOption) (*ListLoginsResponse, error)
	// ListWorktrees lists a repo's worktrees with live reconciliation status —
	// `lumberjack repositories NAME worktrees`.
	ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error)
	// DeleteWorktree removes a worktree —
	// `lumberjack repositories NAME worktree BRANCH_OR_DIRECTORY_NAME delete`.
	DeleteWorktree(ctx context.Context, in *DeleteWorktreeRequest, opts ...grpc.CallOption) (*DeleteWorktreeResponse, error)
	// Sync reconciles worktrees against open PRs. With an empty repository it
	// syncs everything (`lumberjack repositories --sync`); with one set it syncs
	// just that repo (`lumberjack sync`). Progress is streamed back as it runs.
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncResponse], error)
}

type lumberjackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLumberjackServiceClient(cc grpc.ClientConnInterface) LumberjackServiceClient {
	return &lumberjackServiceClient{cc}
}

func (c *lumberjackServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LumberjackService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*InitRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitRepositoryResponse)
	err := c.cc.Invoke(ctx, LumberjackService_InitRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, LumberjackService_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*GetRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepositoryResponse)
	err := c.cc.Invoke(ctx, LumberjackService_GetRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) SetLogin(ctx context.Context, in *SetLoginRequest, opts ...grpc.CallOption) (*SetLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLoginResponse)
	err := c.cc.Invoke(ctx, LumberjackService_SetLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) ListLogins(ctx context.Context, in *ListLoginsRequest, opts ...grpc.CallOption) (*ListLoginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoginsResponse)
	err := c.cc.Invoke(ctx, LumberjackService_ListLogins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorktreesResponse)
	err := c.cc.Invoke(ctx, LumberjackService_ListWorktrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) DeleteWorktree(ctx context.Context, in *DeleteWorktreeRequest, opts ...grpc.CallOption) (*DeleteWorktreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorktreeResponse)
	err := c.cc.Invoke(ctx, LumberjackService_DeleteWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumberjackServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LumberjackService_ServiceDesc.Streams[0], LumberjackService_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, SyncResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumberjackService_SyncClient = grpc.ServerStreamingClient[SyncResponse]

// LumberjackServiceServer is the server API for LumberjackService service.
// All implementations must embed UnimplementedLumberjackServiceServer
// for forward compatibility.
//
// LumberjackService is served by `lumberjack daemon` over a local Unix domain
// socket (LUMBERJACK_SOCKET_PATH). Every user-facing CLI command maps to one
// of these RPCs.
type LumberjackServiceServer interface {
	// Health reports that the daemon is up. The CLI uses it to detect whether a
	// daemon is running before issuing other calls.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// InitRepository registers a repo — `lumberjack init .`.
	InitRepository(context.Context, *InitRepositoryRequest) (*InitRepositoryResponse, error)
	// ListRepositories lists tracked repos — `lumberjack repositories`.
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
	// GetRepository returns one repo's last-sync detail —
	// `lumberjack repositories NAME`.
	GetRepository(context.Context, *GetRepositoryRequest) (*GetRepositoryResponse, error)
	// SetLogin sets the gh account a repository operates under —
	// `lumberjack repositories NAME set-login LOGIN` or, from within a tracked
	// checkout, `lumberjack set-login LOGIN`. The daemon rejects a login that gh
	// is not authenticated as for the repository's host, or one that authenticates
	// but cannot reach the repository on GitHub.
	SetLogin(context.Context, *SetLoginRequest) (*SetLoginResponse, error)
	// ListLogins returns the gh accounts authenticated for a repository's host —
	// the candidates set-login accepts. The CLI uses it to offer an interactive
	// picker when `set-login` is run without a login.
	ListLogins(context.Context, *ListLoginsRequest) (*ListLoginsResponse, error)
	// ListWorktrees lists a repo's worktrees with live reconciliation status —
	// `lumberjack repositories NAME worktrees`.
	ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error)
	// DeleteWorktree removes a worktree —
	// `lumberjack repositories NAME worktree BRANCH_OR_DIRECTORY_NAME delete`.
	DeleteWorktree(context.Context, *DeleteWorktreeRequest) (*DeleteWorktreeResponse, error)
	// Sync reconciles worktrees against open PRs. With an empty repository it
	// syncs everything (`lumberjack repositories --sync`); with one set it syncs
	// just that repo (`lumberjack sync`). Progress is streamed back as it runs.
	Sync(*SyncRequest, grpc.ServerStreamingServer[SyncResponse]) error
	mustEmbedUnimplementedLumberjackServiceServer()
}

// UnimplementedLumberjackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLumberjackServiceServer struct{}

func (UnimplementedLumberjackServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLumberjackServiceServer) InitRepository(context.Context, *InitRepositoryRequest) (*InitRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitRepository not implemented")
}
func (UnimplementedLumberjackServiceServer) ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedLumberjackServiceServer) GetRepository(context.Context, *GetRepositoryRequest) (*GetRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepository not implemented")
}
func (UnimplementedLumberjackServiceServer) SetLogin(context.Context, *SetLoginRequest) (*SetLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogin not implemented")
}
func (UnimplementedLumberjackServiceServer) ListLogins(context.Context, *ListLoginsRequest) (*ListLoginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLogins not implemented")
}
func (UnimplementedLumberjackServiceServer) ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorktrees not implemented")
}
func (UnimplementedLumberjackServiceServer) DeleteWorktree(context.Context, *DeleteWorktreeRequest) (*DeleteWorktreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorktree not implemented")
}
func (UnimplementedLumberjackServiceServer) Sync(*SyncRequest, grpc.ServerStreamingServer[SyncResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedLumberjackServiceServer) mustEmbedUnimplementedLumberjackServiceServer() {}
func (UnimplementedLumberjackServiceServer) testEmbeddedByValue()                           {}

// UnsafeLumberjackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LumberjackServiceServer will
// result in compilation errors.
type UnsafeLumberjackServiceServer interface {
	mustEmbedUnimplementedLumberjackServiceServer()
}

func RegisterLumberjackServiceServer(s grpc.ServiceRegistrar, srv LumberjackServiceServer) {
	// If the following call pancis, it indicates UnimplementedLumberjackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LumberjackService_ServiceDesc, srv)
}

func _LumberjackService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_InitRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).InitRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_InitRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).InitRepository(ctx, req.(*InitRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_GetRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).GetRepository(ctx, req.(*GetRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_SetLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).SetLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_SetLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).SetLogin(ctx, req.(*SetLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_ListLogins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).ListLogins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_ListLogins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).ListLogins(ctx, req.(*ListLoginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_ListWorktrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorktreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).ListWorktrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_ListWorktrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).ListWorktrees(ctx, req.(*ListWorktreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_DeleteWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumberjackServiceServer).DeleteWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumberjackService_DeleteWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumberjackServiceServer).DeleteWorktree(ctx, req.(*DeleteWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumberjackService_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LumberjackServiceServer).Sync(m, &grpc.GenericServerStream[SyncRequest, SyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumberjackService_SyncServer = grpc.ServerStreamingServer[SyncResponse]

// LumberjackService_ServiceDesc is the grpc.ServiceDesc for LumberjackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LumberjackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumberjack.v1.LumberjackService",
	HandlerType: (*LumberjackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _LumberjackService_Health_Handler,
		},
		{
			MethodName: "InitRepository",
			Handler:    _LumberjackService_InitRepository_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _LumberjackService_ListRepositories_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _LumberjackService_GetRepository_Handler,
		},
		{
			MethodName: "SetLogin",
			Handler:    _LumberjackService_SetLogin_Handler,
		},
		{
			MethodName: "ListLogins",
			Handler:    _LumberjackService_ListLogins_Handler,
		},
		{
			MethodName: "ListWorktrees",
			Handler:    _LumberjackService_ListWorktrees_Handler,
		},
		{
			MethodName: "DeleteWorktree",
			Handler:    _LumberjackService_DeleteWorktree_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _LumberjackService_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lumberjack/v1/lumberjack.proto",
}
