// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: lumberjack/v1/lumberjack.proto

// Package lumberjack.v1 is the gRPC contract between the Lumberjack CLI
// (client) and the background daemon (server). The daemon owns the database
// and all worktree operations; the CLI is a thin client that calls into this
// API. See docs/prd.md ("Architecture: client / server split") and AGENTS.md.
//
// `lumberjack doctor` deliberately has no RPC here: it checks host
// prerequisites (git/gh) and must work even when the daemon is not running, so
// it stays entirely CLI-local.

package lumberjackv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncStatus mirrors schema.SyncStatus* (see internal/database/schema).
type SyncStatus int32

const (
	SyncStatus_SYNC_STATUS_UNSPECIFIED SyncStatus = 0
	SyncStatus_SYNC_STATUS_OK          SyncStatus = 1
	SyncStatus_SYNC_STATUS_ERROR       SyncStatus = 2
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_OK",
		2: "SYNC_STATUS_ERROR",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED": 0,
		"SYNC_STATUS_OK":          1,
		"SYNC_STATUS_ERROR":       2,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lumberjack_v1_lumberjack_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_lumberjack_v1_lumberjack_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{0}
}

// CreatedBy mirrors schema.CreatedBy* — the safety rail that stops the daemon
// deleting a worktree a human made by hand.
type CreatedBy int32

const (
	CreatedBy_CREATED_BY_UNSPECIFIED CreatedBy = 0
	CreatedBy_CREATED_BY_LUMBERJACK  CreatedBy = 1
	CreatedBy_CREATED_BY_PREEXISTING CreatedBy = 2
)

// Enum value maps for CreatedBy.
var (
	CreatedBy_name = map[int32]string{
		0: "CREATED_BY_UNSPECIFIED",
		1: "CREATED_BY_LUMBERJACK",
		2: "CREATED_BY_PREEXISTING",
	}
	CreatedBy_value = map[string]int32{
		"CREATED_BY_UNSPECIFIED": 0,
		"CREATED_BY_LUMBERJACK":  1,
		"CREATED_BY_PREEXISTING": 2,
	}
)

func (x CreatedBy) Enum() *CreatedBy {
	p := new(CreatedBy)
	*p = x
	return p
}

func (x CreatedBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreatedBy) Descriptor() protoreflect.EnumDescriptor {
	return file_lumberjack_v1_lumberjack_proto_enumTypes[1].Descriptor()
}

func (CreatedBy) Type() protoreflect.EnumType {
	return &file_lumberjack_v1_lumberjack_proto_enumTypes[1]
}

func (x CreatedBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreatedBy.Descriptor instead.
func (CreatedBy) EnumDescriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{1}
}

// WorktreeAction is what a sync (or init) did to a single branch's worktree,
// reported per branch so the CLI can render a branch/PR/action table.
type WorktreeAction int32

const (
	WorktreeAction_WORKTREE_ACTION_UNSPECIFIED WorktreeAction = 0
	// Created a new worktree for an open PR.
	WorktreeAction_WORKTREE_ACTION_CHECKED_OUT WorktreeAction = 1
	// Adopted a directory git already had checked out into tracking.
	WorktreeAction_WORKTREE_ACTION_ADOPTED WorktreeAction = 2
	// Linked an already-tracked worktree to its open PR.
	WorktreeAction_WORKTREE_ACTION_UPDATED WorktreeAction = 3
	// Removed a worktree whose PR has closed.
	WorktreeAction_WORKTREE_ACTION_DELETED WorktreeAction = 4
	// Kept a closed-PR worktree that still holds unmerged local work.
	WorktreeAction_WORKTREE_ACTION_RETAINED WorktreeAction = 5
)

// Enum value maps for WorktreeAction.
var (
	WorktreeAction_name = map[int32]string{
		0: "WORKTREE_ACTION_UNSPECIFIED",
		1: "WORKTREE_ACTION_CHECKED_OUT",
		2: "WORKTREE_ACTION_ADOPTED",
		3: "WORKTREE_ACTION_UPDATED",
		4: "WORKTREE_ACTION_DELETED",
		5: "WORKTREE_ACTION_RETAINED",
	}
	WorktreeAction_value = map[string]int32{
		"WORKTREE_ACTION_UNSPECIFIED": 0,
		"WORKTREE_ACTION_CHECKED_OUT": 1,
		"WORKTREE_ACTION_ADOPTED":     2,
		"WORKTREE_ACTION_UPDATED":     3,
		"WORKTREE_ACTION_DELETED":     4,
		"WORKTREE_ACTION_RETAINED":    5,
	}
)

func (x WorktreeAction) Enum() *WorktreeAction {
	p := new(WorktreeAction)
	*p = x
	return p
}

func (x WorktreeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorktreeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_lumberjack_v1_lumberjack_proto_enumTypes[2].Descriptor()
}

func (WorktreeAction) Type() protoreflect.EnumType {
	return &file_lumberjack_v1_lumberjack_proto_enumTypes[2]
}

func (x WorktreeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorktreeAction.Descriptor instead.
func (WorktreeAction) EnumDescriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{2}
}

// WorktreeChange is one per-branch progress row: what happened to the worktree
// for a branch, the PR it relates to (absent when there is none, e.g. an
// adoption before its PR is known), and an optional human-readable detail
// (e.g. the reason a worktree was retained).
type WorktreeChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	PrNumber      *int64                 `protobuf:"varint,2,opt,name=pr_number,json=prNumber,proto3,oneof" json:"pr_number,omitempty"`
	Action        WorktreeAction         `protobuf:"varint,3,opt,name=action,proto3,enum=lumberjack.v1.WorktreeAction" json:"action,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorktreeChange) Reset() {
	*x = WorktreeChange{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorktreeChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorktreeChange) ProtoMessage() {}

func (x *WorktreeChange) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorktreeChange.ProtoReflect.Descriptor instead.
func (*WorktreeChange) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{0}
}

func (x *WorktreeChange) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WorktreeChange) GetPrNumber() int64 {
	if x != nil && x.PrNumber != nil {
		return *x.PrNumber
	}
	return 0
}

func (x *WorktreeChange) GetAction() WorktreeAction {
	if x != nil {
		return x.Action
	}
	return WorktreeAction_WORKTREE_ACTION_UNSPECIFIED
}

func (x *WorktreeChange) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Repository is one tracked repo. Fields mirror the `repositories` table
// (docs/schema.md); mutable PR state is never carried here.
type Repository struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalPath         string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	WorktreeParentDir string                 `protobuf:"bytes,3,opt,name=worktree_parent_dir,json=worktreeParentDir,proto3" json:"worktree_parent_dir,omitempty"`
	DirPrefix         string                 `protobuf:"bytes,4,opt,name=dir_prefix,json=dirPrefix,proto3" json:"dir_prefix,omitempty"`
	GithubOwner       string                 `protobuf:"bytes,5,opt,name=github_owner,json=githubOwner,proto3" json:"github_owner,omitempty"`
	GithubName        string                 `protobuf:"bytes,6,opt,name=github_name,json=githubName,proto3" json:"github_name,omitempty"`
	DefaultRemote     string                 `protobuf:"bytes,7,opt,name=default_remote,json=defaultRemote,proto3" json:"default_remote,omitempty"`
	Host              string                 `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	LastSyncedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_synced_at,json=lastSyncedAt,proto3,oneof" json:"last_synced_at,omitempty"`
	LastSyncStatus    SyncStatus             `protobuf:"varint,10,opt,name=last_sync_status,json=lastSyncStatus,proto3,enum=lumberjack.v1.SyncStatus" json:"last_sync_status,omitempty"`
	LastSyncError     *string                `protobuf:"bytes,11,opt,name=last_sync_error,json=lastSyncError,proto3,oneof" json:"last_sync_error,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The gh account this repo was registered under; the daemon switches to it
	// before operating on the repo. Empty for repos tracked before login capture.
	Login         string `protobuf:"bytes,13,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{1}
}

func (x *Repository) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Repository) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *Repository) GetWorktreeParentDir() string {
	if x != nil {
		return x.WorktreeParentDir
	}
	return ""
}

func (x *Repository) GetDirPrefix() string {
	if x != nil {
		return x.DirPrefix
	}
	return ""
}

func (x *Repository) GetGithubOwner() string {
	if x != nil {
		return x.GithubOwner
	}
	return ""
}

func (x *Repository) GetGithubName() string {
	if x != nil {
		return x.GithubName
	}
	return ""
}

func (x *Repository) GetDefaultRemote() string {
	if x != nil {
		return x.DefaultRemote
	}
	return ""
}

func (x *Repository) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Repository) GetLastSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncedAt
	}
	return nil
}

func (x *Repository) GetLastSyncStatus() SyncStatus {
	if x != nil {
		return x.LastSyncStatus
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *Repository) GetLastSyncError() string {
	if x != nil && x.LastSyncError != nil {
		return *x.LastSyncError
	}
	return ""
}

func (x *Repository) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Repository) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

// Worktree is the live view of a local worktree: the stored branch <-> directory
// mapping plus reconciliation status computed fresh from git at request time
// (never cached — see docs/schema.md "Derived live, not stored").
type Worktree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchName    string                 `protobuf:"bytes,1,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	DirectoryPath string                 `protobuf:"bytes,2,opt,name=directory_path,json=directoryPath,proto3" json:"directory_path,omitempty"`
	// Absent for an orphaned worktree that has outlived its PR.
	GithubPrNumber *int64                 `protobuf:"varint,3,opt,name=github_pr_number,json=githubPrNumber,proto3,oneof" json:"github_pr_number,omitempty"`
	CreatedBy      CreatedBy              `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3,enum=lumberjack.v1.CreatedBy" json:"created_by,omitempty"`
	LastSyncedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_synced_at,json=lastSyncedAt,proto3,oneof" json:"last_synced_at,omitempty"`
	// --- derived live from git, not persisted ---
	// needs_reconciliation is true when the worktree can't be safely auto-removed
	// (dirty tree, local-only commits, or otherwise diverged).
	NeedsReconciliation bool `protobuf:"varint,6,opt,name=needs_reconciliation,json=needsReconciliation,proto3" json:"needs_reconciliation,omitempty"`
	// dirty is true when the working tree has uncommitted changes.
	Dirty bool `protobuf:"varint,7,opt,name=dirty,proto3" json:"dirty,omitempty"`
	// orphaned is true when the PR has been merged/closed but the worktree was
	// retained because it still holds unmerged local work.
	Orphaned bool `protobuf:"varint,8,opt,name=orphaned,proto3" json:"orphaned,omitempty"`
	// local_only_commits counts commits present locally but not in the merged
	// remote branch — the count surfaced when confirming a delete.
	LocalOnlyCommits int64 `protobuf:"varint,9,opt,name=local_only_commits,json=localOnlyCommits,proto3" json:"local_only_commits,omitempty"`
	// reconciliation_note is a human-readable summary; empty when in sync.
	ReconciliationNote string `protobuf:"bytes,10,opt,name=reconciliation_note,json=reconciliationNote,proto3" json:"reconciliation_note,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Worktree) Reset() {
	*x = Worktree{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worktree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worktree) ProtoMessage() {}

func (x *Worktree) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worktree.ProtoReflect.Descriptor instead.
func (*Worktree) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{2}
}

func (x *Worktree) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *Worktree) GetDirectoryPath() string {
	if x != nil {
		return x.DirectoryPath
	}
	return ""
}

func (x *Worktree) GetGithubPrNumber() int64 {
	if x != nil && x.GithubPrNumber != nil {
		return *x.GithubPrNumber
	}
	return 0
}

func (x *Worktree) GetCreatedBy() CreatedBy {
	if x != nil {
		return x.CreatedBy
	}
	return CreatedBy_CREATED_BY_UNSPECIFIED
}

func (x *Worktree) GetLastSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncedAt
	}
	return nil
}

func (x *Worktree) GetNeedsReconciliation() bool {
	if x != nil {
		return x.NeedsReconciliation
	}
	return false
}

func (x *Worktree) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

func (x *Worktree) GetOrphaned() bool {
	if x != nil {
		return x.Orphaned
	}
	return false
}

func (x *Worktree) GetLocalOnlyCommits() int64 {
	if x != nil {
		return x.LocalOnlyCommits
	}
	return 0
}

func (x *Worktree) GetReconciliationNote() string {
	if x != nil {
		return x.ReconciliationNote
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type InitRepositoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to the repo being registered (`lumberjack init .` resolves
	// "." to the current directory before calling).
	LocalPath     string `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRepositoryRequest) Reset() {
	*x = InitRepositoryRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRepositoryRequest) ProtoMessage() {}

func (x *InitRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRepositoryRequest.ProtoReflect.Descriptor instead.
func (*InitRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{5}
}

func (x *InitRepositoryRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

type InitRepositoryResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Repository *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Deprecated: superseded by `adopted` (field 3), which carries the full
	// per-branch change so init can render the same branch/PR/action table as
	// sync. No longer populated by the daemon.
	//
	// Deprecated: Marked as deprecated in lumberjack/v1/lumberjack.proto.
	AdoptedBranches []string `protobuf:"bytes,2,rep,name=adopted_branches,json=adoptedBranches,proto3" json:"adopted_branches,omitempty"`
	// The worktrees adopted into tracking during init — directories git had
	// already checked out for this repo but Lumberjack did not yet track (each
	// with action ADOPTED and no PR number yet). Empty for a fresh checkout with
	// no sibling worktrees.
	Adopted       []*WorktreeChange `protobuf:"bytes,3,rep,name=adopted,proto3" json:"adopted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRepositoryResponse) Reset() {
	*x = InitRepositoryResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRepositoryResponse) ProtoMessage() {}

func (x *InitRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRepositoryResponse.ProtoReflect.Descriptor instead.
func (*InitRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{6}
}

func (x *InitRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

// Deprecated: Marked as deprecated in lumberjack/v1/lumberjack.proto.
func (x *InitRepositoryResponse) GetAdoptedBranches() []string {
	if x != nil {
		return x.AdoptedBranches
	}
	return nil
}

func (x *InitRepositoryResponse) GetAdopted() []*WorktreeChange {
	if x != nil {
		return x.Adopted
	}
	return nil
}

type ListRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{7}
}

type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{8}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type GetRepositoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A repository name (dir prefix / GitHub name) or its local path; the daemon
	// resolves either form.
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryRequest) Reset() {
	*x = GetRepositoryRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryRequest) ProtoMessage() {}

func (x *GetRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{9}
}

func (x *GetRepositoryRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type GetRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryResponse) Reset() {
	*x = GetRepositoryResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryResponse) ProtoMessage() {}

func (x *GetRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{10}
}

func (x *GetRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type SetLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A repository name (dir prefix / GitHub name) or its local path; the daemon
	// resolves either form.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// The gh account login the repository should operate under henceforth.
	Login         string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoginRequest) Reset() {
	*x = SetLoginRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoginRequest) ProtoMessage() {}

func (x *SetLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoginRequest.ProtoReflect.Descriptor instead.
func (*SetLoginRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{11}
}

func (x *SetLoginRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SetLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type SetLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoginResponse) Reset() {
	*x = SetLoginResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoginResponse) ProtoMessage() {}

func (x *SetLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoginResponse.ProtoReflect.Descriptor instead.
func (*SetLoginResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{12}
}

func (x *SetLoginResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type ListLoginsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A repository name (dir prefix / GitHub name) or its local path; the daemon
	// resolves either form and lists the gh accounts for its host.
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoginsRequest) Reset() {
	*x = ListLoginsRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoginsRequest) ProtoMessage() {}

func (x *ListLoginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoginsRequest.ProtoReflect.Descriptor instead.
func (*ListLoginsRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{13}
}

func (x *ListLoginsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type ListLoginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The gh account logins authenticated for the repository's host.
	Logins []string `protobuf:"bytes,1,rep,name=logins,proto3" json:"logins,omitempty"`
	// The login the repository currently operates under, if any — the CLI
	// pre-selects it in the picker. Empty for repos tracked before login capture.
	Current       string `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoginsResponse) Reset() {
	*x = ListLoginsResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoginsResponse) ProtoMessage() {}

func (x *ListLoginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoginsResponse.ProtoReflect.Descriptor instead.
func (*ListLoginsResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{14}
}

func (x *ListLoginsResponse) GetLogins() []string {
	if x != nil {
		return x.Logins
	}
	return nil
}

func (x *ListLoginsResponse) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

type ListWorktreesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesRequest) Reset() {
	*x = ListWorktreesRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesRequest) ProtoMessage() {}

func (x *ListWorktreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesRequest.ProtoReflect.Descriptor instead.
func (*ListWorktreesRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{15}
}

func (x *ListWorktreesRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type ListWorktreesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worktrees     []*Worktree            `protobuf:"bytes,1,rep,name=worktrees,proto3" json:"worktrees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesResponse) Reset() {
	*x = ListWorktreesResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesResponse) ProtoMessage() {}

func (x *ListWorktreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesResponse.ProtoReflect.Descriptor instead.
func (*ListWorktreesResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{16}
}

func (x *ListWorktreesResponse) GetWorktrees() []*Worktree {
	if x != nil {
		return x.Worktrees
	}
	return nil
}

type DeleteWorktreeRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Repository string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Branch name or directory name identifying the worktree.
	Worktree string `protobuf:"bytes,2,opt,name=worktree,proto3" json:"worktree,omitempty"`
	// Proceed even when local commits would be lost. The CLI sets this only after
	// the user confirms the warning returned by a first, unforced attempt.
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorktreeRequest) Reset() {
	*x = DeleteWorktreeRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorktreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorktreeRequest) ProtoMessage() {}

func (x *DeleteWorktreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorktreeRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorktreeRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteWorktreeRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *DeleteWorktreeRequest) GetWorktree() string {
	if x != nil {
		return x.Worktree
	}
	return ""
}

func (x *DeleteWorktreeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteWorktreeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Deleted bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// True when the worktree's local tip is ahead of the merged remote: the CLI
	// must warn the user and retry with force=true to actually delete.
	RequiresConfirmation bool `protobuf:"varint,2,opt,name=requires_confirmation,json=requiresConfirmation,proto3" json:"requires_confirmation,omitempty"`
	// Number of commits that would be lost, for the confirmation warning.
	CommitsAtRisk int64  `protobuf:"varint,3,opt,name=commits_at_risk,json=commitsAtRisk,proto3" json:"commits_at_risk,omitempty"`
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorktreeResponse) Reset() {
	*x = DeleteWorktreeResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorktreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorktreeResponse) ProtoMessage() {}

func (x *DeleteWorktreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorktreeResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorktreeResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteWorktreeResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteWorktreeResponse) GetRequiresConfirmation() bool {
	if x != nil {
		return x.RequiresConfirmation
	}
	return false
}

func (x *DeleteWorktreeResponse) GetCommitsAtRisk() int64 {
	if x != nil {
		return x.CommitsAtRisk
	}
	return 0
}

func (x *DeleteWorktreeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRepositoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A repository name (dir prefix / GitHub name) or its local path; the daemon
	// resolves either form.
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepositoryRequest) Reset() {
	*x = DeleteRepositoryRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryRequest) ProtoMessage() {}

func (x *DeleteRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRepositoryRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type DeleteRepositoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of worktree rows removed alongside the repository.
	WorktreesRemoved int64  `protobuf:"varint,1,opt,name=worktrees_removed,json=worktreesRemoved,proto3" json:"worktrees_removed,omitempty"`
	Message          string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteRepositoryResponse) Reset() {
	*x = DeleteRepositoryResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryResponse) ProtoMessage() {}

func (x *DeleteRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRepositoryResponse) GetWorktreesRemoved() int64 {
	if x != nil {
		return x.WorktreesRemoved
	}
	return 0
}

func (x *DeleteRepositoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty syncs every tracked repository; set syncs just that one.
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{21}
}

func (x *SyncRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

// SyncResponse is one progress update in a Sync stream. Multiple events may be
// emitted per repository; the last one for a repo has completed = true and
// carries its summary.
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which repository this event concerns.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Human-readable progress line, for events that are not a per-branch worktree
	// change (worktree changes use `change` instead).
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// True on the final event for this repository.
	Completed bool `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	// Populated when completed = true.
	Summary *SyncSummary `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	// A per-branch worktree change (checked out / adopted / updated / deleted /
	// retained), for progress events that concern one branch. Absent on the
	// completion event and on plain `message` events.
	Change        *WorktreeChange `protobuf:"bytes,5,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{22}
}

func (x *SyncResponse) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *SyncResponse) GetSummary() *SyncSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *SyncResponse) GetChange() *WorktreeChange {
	if x != nil {
		return x.Change
	}
	return nil
}

type SyncSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           SyncStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=lumberjack.v1.SyncStatus" json:"status,omitempty"`
	WorktreesCreated int64                  `protobuf:"varint,2,opt,name=worktrees_created,json=worktreesCreated,proto3" json:"worktrees_created,omitempty"`
	WorktreesRemoved int64                  `protobuf:"varint,3,opt,name=worktrees_removed,json=worktreesRemoved,proto3" json:"worktrees_removed,omitempty"`
	Error            *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncSummary) Reset() {
	*x = SyncSummary{}
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSummary) ProtoMessage() {}

func (x *SyncSummary) ProtoReflect() protoreflect.Message {
	mi := &file_lumberjack_v1_lumberjack_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSummary.ProtoReflect.Descriptor instead.
func (*SyncSummary) Descriptor() ([]byte, []int) {
	return file_lumberjack_v1_lumberjack_proto_rawDescGZIP(), []int{23}
}

func (x *SyncSummary) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *SyncSummary) GetWorktreesCreated() int64 {
	if x != nil {
		return x.WorktreesCreated
	}
	return 0
}

func (x *SyncSummary) GetWorktreesRemoved() int64 {
	if x != nil {
		return x.WorktreesRemoved
	}
	return 0
}

func (x *SyncSummary) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_lumberjack_v1_lumberjack_proto protoreflect.FileDescriptor

const file_lumberjack_v1_lumberjack_proto_rawDesc = "" +
	"\n" +
	"\x1elumberjack/v1/lumberjack.proto\x12\rlumberjack.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\x0eWorktreeChange\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12 \n" +
	"\tpr_number\x18\x02 \x01(\x03H\x00R\bprNumber\x88\x01\x01\x125\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1d.lumberjack.v1.WorktreeActionR\x06action\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detailB\f\n" +
	"\n" +
	"_pr_number\"\xba\x04\n" +
	"\n" +
	"Repository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x12.\n" +
	"\x13worktree_parent_dir\x18\x03 \x01(\tR\x11worktreeParentDir\x12\x1d\n" +
	"\n" +
	"dir_prefix\x18\x04 \x01(\tR\tdirPrefix\x12!\n" +
	"\fgithub_owner\x18\x05 \x01(\tR\vgithubOwner\x12\x1f\n" +
	"\vgithub_name\x18\x06 \x01(\tR\n" +
	"githubName\x12%\n" +
	"\x0edefault_remote\x18\a \x01(\tR\rdefaultRemote\x12\x12\n" +
	"\x04host\x18\b \x01(\tR\x04host\x12E\n" +
	"\x0elast_synced_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\flastSyncedAt\x88\x01\x01\x12C\n" +
	"\x10last_sync_status\x18\n" +
	" \x01(\x0e2\x19.lumberjack.v1.SyncStatusR\x0elastSyncStatus\x12+\n" +
	"\x0flast_sync_error\x18\v \x01(\tH\x01R\rlastSyncError\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05login\x18\r \x01(\tR\x05loginB\x11\n" +
	"\x0f_last_synced_atB\x12\n" +
	"\x10_last_sync_error\"\xed\x03\n" +
	"\bWorktree\x12\x1f\n" +
	"\vbranch_name\x18\x01 \x01(\tR\n" +
	"branchName\x12%\n" +
	"\x0edirectory_path\x18\x02 \x01(\tR\rdirectoryPath\x12-\n" +
	"\x10github_pr_number\x18\x03 \x01(\x03H\x00R\x0egithubPrNumber\x88\x01\x01\x127\n" +
	"\n" +
	"created_by\x18\x04 \x01(\x0e2\x18.lumberjack.v1.CreatedByR\tcreatedBy\x12E\n" +
	"\x0elast_synced_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\flastSyncedAt\x88\x01\x01\x121\n" +
	"\x14needs_reconciliation\x18\x06 \x01(\bR\x13needsReconciliation\x12\x14\n" +
	"\x05dirty\x18\a \x01(\bR\x05dirty\x12\x1a\n" +
	"\borphaned\x18\b \x01(\bR\borphaned\x12,\n" +
	"\x12local_only_commits\x18\t \x01(\x03R\x10localOnlyCommits\x12/\n" +
	"\x13reconciliation_note\x18\n" +
	" \x01(\tR\x12reconciliationNoteB\x13\n" +
	"\x11_github_pr_numberB\x11\n" +
	"\x0f_last_synced_at\"\x0f\n" +
	"\rHealthRequest\"e\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"6\n" +
	"\x15InitRepositoryRequest\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\"\xbb\x01\n" +
	"\x16InitRepositoryResponse\x129\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x19.lumberjack.v1.RepositoryR\n" +
	"repository\x12-\n" +
	"\x10adopted_branches\x18\x02 \x03(\tB\x02\x18\x01R\x0fadoptedBranches\x127\n" +
	"\aadopted\x18\x03 \x03(\v2\x1d.lumberjack.v1.WorktreeChangeR\aadopted\"\x19\n" +
	"\x17ListRepositoriesRequest\"Y\n" +
	"\x18ListRepositoriesResponse\x12=\n" +
	"\frepositories\x18\x01 \x03(\v2\x19.lumberjack.v1.RepositoryR\frepositories\"6\n" +
	"\x14GetRepositoryRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"R\n" +
	"\x15GetRepositoryResponse\x129\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x19.lumberjack.v1.RepositoryR\n" +
	"repository\"G\n" +
	"\x0fSetLoginRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\"M\n" +
	"\x10SetLoginResponse\x129\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x19.lumberjack.v1.RepositoryR\n" +
	"repository\"3\n" +
	"\x11ListLoginsRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"F\n" +
	"\x12ListLoginsResponse\x12\x16\n" +
	"\x06logins\x18\x01 \x03(\tR\x06logins\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\tR\acurrent\"6\n" +
	"\x14ListWorktreesRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"N\n" +
	"\x15ListWorktreesResponse\x125\n" +
	"\tworktrees\x18\x01 \x03(\v2\x17.lumberjack.v1.WorktreeR\tworktrees\"i\n" +
	"\x15DeleteWorktreeRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x1a\n" +
	"\bworktree\x18\x02 \x01(\tR\bworktree\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\xa9\x01\n" +
	"\x16DeleteWorktreeResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x123\n" +
	"\x15requires_confirmation\x18\x02 \x01(\bR\x14requiresConfirmation\x12&\n" +
	"\x0fcommits_at_risk\x18\x03 \x01(\x03R\rcommitsAtRisk\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"9\n" +
	"\x17DeleteRepositoryRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"a\n" +
	"\x18DeleteRepositoryResponse\x12+\n" +
	"\x11worktrees_removed\x18\x01 \x01(\x03R\x10worktreesRemoved\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\vSyncRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"\xd3\x01\n" +
	"\fSyncResponse\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x124\n" +
	"\asummary\x18\x04 \x01(\v2\x1a.lumberjack.v1.SyncSummaryR\asummary\x125\n" +
	"\x06change\x18\x05 \x01(\v2\x1d.lumberjack.v1.WorktreeChangeR\x06change\"\xbf\x01\n" +
	"\vSyncSummary\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.lumberjack.v1.SyncStatusR\x06status\x12+\n" +
	"\x11worktrees_created\x18\x02 \x01(\x03R\x10worktreesCreated\x12+\n" +
	"\x11worktrees_removed\x18\x03 \x01(\x03R\x10worktreesRemoved\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error*T\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSYNC_STATUS_OK\x10\x01\x12\x15\n" +
	"\x11SYNC_STATUS_ERROR\x10\x02*^\n" +
	"\tCreatedBy\x12\x1a\n" +
	"\x16CREATED_BY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CREATED_BY_LUMBERJACK\x10\x01\x12\x1a\n" +
	"\x16CREATED_BY_PREEXISTING\x10\x02*\xc7\x01\n" +
	"\x0eWorktreeAction\x12\x1f\n" +
	"\x1bWORKTREE_ACTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bWORKTREE_ACTION_CHECKED_OUT\x10\x01\x12\x1b\n" +
	"\x17WORKTREE_ACTION_ADOPTED\x10\x02\x12\x1b\n" +
	"\x17WORKTREE_ACTION_UPDATED\x10\x03\x12\x1b\n" +
	"\x17WORKTREE_ACTION_DELETED\x10\x04\x12\x1c\n" +
	"\x18WORKTREE_ACTION_RETAINED\x10\x052\xfd\x06\n" +
	"\x11LumberjackService\x12E\n" +
	"\x06Health\x12\x1c.lumberjack.v1.HealthRequest\x1a\x1d.lumberjack.v1.HealthResponse\x12]\n" +
	"\x0eInitRepository\x12$.lumberjack.v1.InitRepositoryRequest\x1a%.lumberjack.v1.InitRepositoryResponse\x12c\n" +
	"\x10ListRepositories\x12&.lumberjack.v1.ListRepositoriesRequest\x1a'.lumberjack.v1.ListRepositoriesResponse\x12Z\n" +
	"\rGetRepository\x12#.lumberjack.v1.GetRepositoryRequest\x1a$.lumberjack.v1.GetRepositoryResponse\x12K\n" +
	"\bSetLogin\x12\x1e.lumberjack.v1.SetLoginRequest\x1a\x1f.lumberjack.v1.SetLoginResponse\x12Q\n" +
	"\n" +
	"ListLogins\x12 .lumberjack.v1.ListLoginsRequest\x1a!.lumberjack.v1.ListLoginsResponse\x12Z\n" +
	"\rListWorktrees\x12#.lumberjack.v1.ListWorktreesRequest\x1a$.lumberjack.v1.ListWorktreesResponse\x12]\n" +
	"\x0eDeleteWorktree\x12$.lumberjack.v1.DeleteWorktreeRequest\x1a%.lumberjack.v1.DeleteWorktreeResponse\x12c\n" +
	"\x10DeleteRepository\x12&.lumberjack.v1.DeleteRepositoryRequest\x1a'.lumberjack.v1.DeleteRepositoryResponse\x12A\n" +
	"\x04Sync\x12\x1a.lumberjack.v1.SyncRequest\x1a\x1b.lumberjack.v1.SyncResponse0\x01BIZGgithub.com/ceilingfish/lumberjack/pkg/client/lumberjack/v1;lumberjackv1b\x06proto3"

var (
	file_lumberjack_v1_lumberjack_proto_rawDescOnce sync.Once
	file_lumberjack_v1_lumberjack_proto_rawDescData []byte
)

func file_lumberjack_v1_lumberjack_proto_rawDescGZIP() []byte {
	file_lumberjack_v1_lumberjack_proto_rawDescOnce.Do(func() {
		file_lumberjack_v1_lumberjack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lumberjack_v1_lumberjack_proto_rawDesc), len(file_lumberjack_v1_lumberjack_proto_rawDesc)))
	})
	return file_lumberjack_v1_lumberjack_proto_rawDescData
}

var file_lumberjack_v1_lumberjack_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lumberjack_v1_lumberjack_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_lumberjack_v1_lumberjack_proto_goTypes = []any{
	(SyncStatus)(0),                  // 0: lumberjack.v1.SyncStatus
	(CreatedBy)(0),                   // 1: lumberjack.v1.CreatedBy
	(WorktreeAction)(0),              // 2: lumberjack.v1.WorktreeAction
	(*WorktreeChange)(nil),           // 3: lumberjack.v1.WorktreeChange
	(*Repository)(nil),               // 4: lumberjack.v1.Repository
	(*Worktree)(nil),                 // 5: lumberjack.v1.Worktree
	(*HealthRequest)(nil),            // 6: lumberjack.v1.HealthRequest
	(*HealthResponse)(nil),           // 7: lumberjack.v1.HealthResponse
	(*InitRepositoryRequest)(nil),    // 8: lumberjack.v1.InitRepositoryRequest
	(*InitRepositoryResponse)(nil),   // 9: lumberjack.v1.InitRepositoryResponse
	(*ListRepositoriesRequest)(nil),  // 10: lumberjack.v1.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil), // 11: lumberjack.v1.ListRepositoriesResponse
	(*GetRepositoryRequest)(nil),     // 12: lumberjack.v1.GetRepositoryRequest
	(*GetRepositoryResponse)(nil),    // 13: lumberjack.v1.GetRepositoryResponse
	(*SetLoginRequest)(nil),          // 14: lumberjack.v1.SetLoginRequest
	(*SetLoginResponse)(nil),         // 15: lumberjack.v1.SetLoginResponse
	(*ListLoginsRequest)(nil),        // 16: lumberjack.v1.ListLoginsRequest
	(*ListLoginsResponse)(nil),       // 17: lumberjack.v1.ListLoginsResponse
	(*ListWorktreesRequest)(nil),     // 18: lumberjack.v1.ListWorktreesRequest
	(*ListWorktreesResponse)(nil),    // 19: lumberjack.v1.ListWorktreesResponse
	(*DeleteWorktreeRequest)(nil),    // 20: lumberjack.v1.DeleteWorktreeRequest
	(*DeleteWorktreeResponse)(nil),   // 21: lumberjack.v1.DeleteWorktreeResponse
	(*DeleteRepositoryRequest)(nil),  // 22: lumberjack.v1.DeleteRepositoryRequest
	(*DeleteRepositoryResponse)(nil), // 23: lumberjack.v1.DeleteRepositoryResponse
	(*SyncRequest)(nil),              // 24: lumberjack.v1.SyncRequest
	(*SyncResponse)(nil),             // 25: lumberjack.v1.SyncResponse
	(*SyncSummary)(nil),              // 26: lumberjack.v1.SyncSummary
	(*timestamppb.Timestamp)(nil),    // 27: google.protobuf.Timestamp
}
var file_lumberjack_v1_lumberjack_proto_depIdxs = []int32{
	2,  // 0: lumberjack.v1.WorktreeChange.action:type_name -> lumberjack.v1.WorktreeAction
	27, // 1: lumberjack.v1.Repository.last_synced_at:type_name -> google.protobuf.Timestamp
	0,  // 2: lumberjack.v1.Repository.last_sync_status:type_name -> lumberjack.v1.SyncStatus
	27, // 3: lumberjack.v1.Repository.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: lumberjack.v1.Worktree.created_by:type_name -> lumberjack.v1.CreatedBy
	27, // 5: lumberjack.v1.Worktree.last_synced_at:type_name -> google.protobuf.Timestamp
	27, // 6: lumberjack.v1.HealthResponse.started_at:type_name -> google.protobuf.Timestamp
	4,  // 7: lumberjack.v1.InitRepositoryResponse.repository:type_name -> lumberjack.v1.Repository
	3,  // 8: lumberjack.v1.InitRepositoryResponse.adopted:type_name -> lumberjack.v1.WorktreeChange
	4,  // 9: lumberjack.v1.ListRepositoriesResponse.repositories:type_name -> lumberjack.v1.Repository
	4,  // 10: lumberjack.v1.GetRepositoryResponse.repository:type_name -> lumberjack.v1.Repository
	4,  // 11: lumberjack.v1.SetLoginResponse.repository:type_name -> lumberjack.v1.Repository
	5,  // 12: lumberjack.v1.ListWorktreesResponse.worktrees:type_name -> lumberjack.v1.Worktree
	26, // 13: lumberjack.v1.SyncResponse.summary:type_name -> lumberjack.v1.SyncSummary
	3,  // 14: lumberjack.v1.SyncResponse.change:type_name -> lumberjack.v1.WorktreeChange
	0,  // 15: lumberjack.v1.SyncSummary.status:type_name -> lumberjack.v1.SyncStatus
	6,  // 16: lumberjack.v1.LumberjackService.Health:input_type -> lumberjack.v1.HealthRequest
	8,  // 17: lumberjack.v1.LumberjackService.InitRepository:input_type -> lumberjack.v1.InitRepositoryRequest
	10, // 18: lumberjack.v1.LumberjackService.ListRepositories:input_type -> lumberjack.v1.ListRepositoriesRequest
	12, // 19: lumberjack.v1.LumberjackService.GetRepository:input_type -> lumberjack.v1.GetRepositoryRequest
	14, // 20: lumberjack.v1.LumberjackService.SetLogin:input_type -> lumberjack.v1.SetLoginRequest
	16, // 21: lumberjack.v1.LumberjackService.ListLogins:input_type -> lumberjack.v1.ListLoginsRequest
	18, // 22: lumberjack.v1.LumberjackService.ListWorktrees:input_type -> lumberjack.v1.ListWorktreesRequest
	20, // 23: lumberjack.v1.LumberjackService.DeleteWorktree:input_type -> lumberjack.v1.DeleteWorktreeRequest
	22, // 24: lumberjack.v1.LumberjackService.DeleteRepository:input_type -> lumberjack.v1.DeleteRepositoryRequest
	24, // 25: lumberjack.v1.LumberjackService.Sync:input_type -> lumberjack.v1.SyncRequest
	7,  // 26: lumberjack.v1.LumberjackService.Health:output_type -> lumberjack.v1.HealthResponse
	9,  // 27: lumberjack.v1.LumberjackService.InitRepository:output_type -> lumberjack.v1.InitRepositoryResponse
	11, // 28: lumberjack.v1.LumberjackService.ListRepositories:output_type -> lumberjack.v1.ListRepositoriesResponse
	13, // 29: lumberjack.v1.LumberjackService.GetRepository:output_type -> lumberjack.v1.GetRepositoryResponse
	15, // 30: lumberjack.v1.LumberjackService.SetLogin:output_type -> lumberjack.v1.SetLoginResponse
	17, // 31: lumberjack.v1.LumberjackService.ListLogins:output_type -> lumberjack.v1.ListLoginsResponse
	19, // 32: lumberjack.v1.LumberjackService.ListWorktrees:output_type -> lumberjack.v1.ListWorktreesResponse
	21, // 33: lumberjack.v1.LumberjackService.DeleteWorktree:output_type -> lumberjack.v1.DeleteWorktreeResponse
	23, // 34: lumberjack.v1.LumberjackService.DeleteRepository:output_type -> lumberjack.v1.DeleteRepositoryResponse
	25, // 35: lumberjack.v1.LumberjackService.Sync:output_type -> lumberjack.v1.SyncResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_lumberjack_v1_lumberjack_proto_init() }
func file_lumberjack_v1_lumberjack_proto_init() {
	if File_lumberjack_v1_lumberjack_proto != nil {
		return
	}
	file_lumberjack_v1_lumberjack_proto_msgTypes[0].OneofWrappers = []any{}
	file_lumberjack_v1_lumberjack_proto_msgTypes[1].OneofWrappers = []any{}
	file_lumberjack_v1_lumberjack_proto_msgTypes[2].OneofWrappers = []any{}
	file_lumberjack_v1_lumberjack_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lumberjack_v1_lumberjack_proto_rawDesc), len(file_lumberjack_v1_lumberjack_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lumberjack_v1_lumberjack_proto_goTypes,
		DependencyIndexes: file_lumberjack_v1_lumberjack_proto_depIdxs,
		EnumInfos:         file_lumberjack_v1_lumberjack_proto_enumTypes,
		MessageInfos:      file_lumberjack_v1_lumberjack_proto_msgTypes,
	}.Build()
	File_lumberjack_v1_lumberjack_proto = out.File
	file_lumberjack_v1_lumberjack_proto_goTypes = nil
	file_lumberjack_v1_lumberjack_proto_depIdxs = nil
}
