#!/usr/bin/env bash
#
# Report coverage per file (lowest first) and fail if total statement coverage
# falls below the threshold.
#
# This runs no tests of its own. `mise run cli:test` writes the Go profile and
# `mise run osx:test` emits the Swift coverage data; the `coverage` task
# depends on both and this reads what they leave behind. Keeping the test runs
# out of here is what lets the Go and Swift toolchains stay wholly separate
# everywhere except this one shared gate.
#
# Generated code is excluded: the committed protobuf stubs (*.pb.go) are
# generated by `buf generate` and never hand-edited (see AGENTS.md), so they
# are not ours to test and would otherwise dominate the total.
#
# Usage: scripts/coverage.sh [threshold]   (threshold defaults to 80)
set -euo pipefail

threshold="${1:-80}"
profile="coverage.out"

if [ ! -f "$profile" ]; then
  echo "error: $profile not found — run 'mise run cli:test' first" >&2
  exit 1
fi

awk -v threshold="$threshold" '
/^mode:/ { next }
/\.pb\.go:/ { next }   # skip generated protobuf/gRPC stubs
{
  file = $1
  sub(/:[0-9]+\.[0-9]+,[0-9]+\.[0-9]+$/, "", file)
  tot[file] += $2
  gtot += $2
  if ($3 > 0) { cov[file] += $2; gcov += $2 }
}
END {
  for (f in tot)
    printf "%6.1f%%  %s\n", (tot[f] ? 100 * cov[f] / tot[f] : 0), f | "sort -n"
  close("sort -n")
  g = gtot ? 100 * gcov / gtot : 0
  printf "-------\n%6.1f%%  TOTAL\n", g
  if (g < threshold) {
    printf "FAIL: total coverage %.1f%% is below the %d%% threshold\n", g, threshold > "/dev/stderr"
    exit 1
  }
}
' "$profile"
